### ISSUE TITLE
UI Style Guide

### ISSUE THREAD

**Issue by dunaevskiy** [evo-doc/front-end#4]
Vytvorit stranku se vsemi prvky, ktere se budou vyskytovat v appce a definovat styly v `./styles/ui/*.scss`.

## Priklad
Budou se pouzivat titles vsech 6 urovni.
```html
<h1>Header H1</h1>
<h2>Header H2</h2>
<h3>Header H3</h3>
<h4>Header H4</h4>
<h5>Header H5</h5>
<h6>Header H6</h6>
```

`./styles/ui/title.scss`
```css
h1 {font : 54px/62px Arial;}
h2 {font : 36px/40px Arial;}
h3 {font : 28px/34px Arial;}
h4 {font : 24px/32px Arial;}
```

Pro vsechny pouzivane typy inputs, odkazu, textu apod. 

Pokud treba nejaky input muze mit vic stylu, tak neco typu:
```css
input[type="password"].valid {border: 1px solid green;}
input[type="password"].invalid {border: 1px solid red;}
```

## Hint
Pokud se ti nechce pridavat odkaz do menu, tak pouzivej consoli. Prikaz pro redirect je
```js
APP._request.redirect("/");
```
